export async function generateDescriptionWithGemini(prompt: string): Promise<string> {
  const apiKey = process.env.GOOGLE_AI_API_KEY

  if (!apiKey) {
    throw new Error('GOOGLE_AI_API_KEY is not configured')
  }

  const systemPrompt = `You are a professional business writer helping to create clear, professional descriptions for quotes and invoices.

The user will describe a service or product, and you should generate a concise, professional description suitable for a business quote or invoice line item.

Keep it professional, clear, and focused on the value provided. Use 2-4 sentences maximum.

Generate only the description, without any preamble or additional commentary.`

  const fullPrompt = `${systemPrompt}\n\nUser request: ${prompt}`

  try {
    // Use REST API directly for better compatibility
    // Using gemini-1.5-pro model (latest stable model)
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: fullPrompt,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 1024,
          },
        }),
      }
    )

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}))
      console.error('Gemini API error:', errorData)
      throw new Error(
        errorData?.error?.message || `API request failed with status ${response.status}`
      )
    }

    const data = await response.json()

    // Debug: log the full response structure
    console.log('Full Gemini response:', JSON.stringify(data, null, 2))

    // Check if we have candidates
    if (!data.candidates || data.candidates.length === 0) {
      console.error('No candidates in Gemini response:', data)
      throw new Error('No response generated by Gemini')
    }

    const candidate = data.candidates[0]

    // Check finish reason
    if (candidate.finishReason === 'MAX_TOKENS') {
      console.warn('Gemini hit max tokens, response may be truncated')
    }

    // Extract text from the response
    const content = candidate.content
    console.log('Content object:', JSON.stringify(content, null, 2))

    if (!content || !content.parts || content.parts.length === 0) {
      console.error('No content parts in Gemini response:', data)
      throw new Error('No content in Gemini response')
    }

    console.log('Content parts:', JSON.stringify(content.parts, null, 2))

    // Get the first text part
    const textPart = content.parts.find((part: any) => part.text)
    if (!textPart || !textPart.text) {
      console.error('No text found in content parts:', content.parts)
      throw new Error('No text content in Gemini response')
    }

    const description = textPart.text.trim()

    if (!description) {
      throw new Error('Empty description generated')
    }

    return description
  } catch (error) {
    console.error('Gemini generation error:', error)

    // Provide more specific error messages
    if (error instanceof Error) {
      if (error.message.includes('API_KEY_INVALID') || error.message.includes('invalid')) {
        throw new Error('Invalid Google AI API key. Please check your GOOGLE_AI_API_KEY.')
      }
      if (error.message.includes('quota') || error.message.includes('limit')) {
        throw new Error('Google AI API quota exceeded. Please try again later.')
      }
      if (error.message.includes('not found') || error.message.includes('404')) {
        throw new Error('Gemini model not available. Please check your API access.')
      }
      // Pass through the original error message for better debugging
      throw new Error(`Gemini error: ${error.message}`)
    }

    throw new Error('Failed to generate description with Gemini')
  }
}
