import OpenAI from 'openai'
import { LineItem } from '@/types'

export interface GeneratedQuote {
  client_name: string
  currency?: string
  items: LineItem[]
  subtotal: number
  tax_rate: number
  tax_amount: number
  total: number
  notes?: string
  valid_until?: string
}

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export async function generateDescriptionWithOpenAI(
  prompt: string,
  history?: Array<{role: string, content: string}>
): Promise<string> {
  try {
    // Build messages array with history
    const messages: Array<{role: 'system' | 'user' | 'assistant', content: string}> = [
      {
        role: 'system',
        content: 'You are Quotla AI, a business assistant for quotes and invoices. Answer professionally and concisely. If you cannot recall specific details from earlier in the conversation, politely ask the user to repeat the information.',
      }
    ]

    // Add last 5 conversation pairs (10 messages) for context
    if (history && history.length > 0) {
      const recentHistory = history.slice(-10)
      recentHistory.forEach(msg => {
        if (msg.role === 'user' || msg.role === 'assistant') {
          messages.push({
            role: msg.role as 'user' | 'assistant',
            content: msg.content
          })
        }
      })
    }

    // Add current prompt
    messages.push({
      role: 'user',
      content: prompt,
    })

    const completion = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages,
      max_tokens: 200,
      temperature: 0.5,
    })

    const description = completion.choices[0]?.message?.content?.trim()

    if (!description) {
      throw new Error('No description generated')
    }

    return description
  } catch (error) {
    console.error('OpenAI generation error:', error)
    throw new Error('Failed to generate description with OpenAI')
  }
}

export async function generateQuoteWithOpenAI(prompt: string): Promise<GeneratedQuote> {
  // Detect currency from prompt
  const lowerPrompt = prompt.toLowerCase()
  let currency = 'USD'

  if (lowerPrompt.includes('ngn') || lowerPrompt.includes('naira') || lowerPrompt.includes('nigeria')) {
    currency = 'NGN'
  } else if (lowerPrompt.includes('eur') || lowerPrompt.includes('euro')) {
    currency = 'EUR'
  } else if (lowerPrompt.includes('gbp') || lowerPrompt.includes('pound')) {
    currency = 'GBP'
  }

  try {
    const completion = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        {
          role: 'system',
          content: `You are a quote generation assistant. Generate a complete quote in JSON format. Always include at least one item with realistic pricing.`,
        },
        {
          role: 'user',
          content: `Create a detailed quote for: ${prompt}

Currency: ${currency}

Return JSON with this structure:
{
  "client_name": "extracted or generic name",
  "currency": "${currency}",
  "items": [
    {
      "description": "item description",
      "quantity": number,
      "unit_price": number,
      "amount": number (quantity * unit_price)
    }
  ],
  "subtotal": number (sum of all item amounts),
  "tax_rate": number (0.1 for 10%),
  "tax_amount": number (subtotal * tax_rate),
  "total": number (subtotal + tax_amount),
  "notes": "optional payment terms or notes",
  "valid_until": "YYYY-MM-DD (30 days from now)"
}`,
        },
      ],
      max_tokens: 1000,
      temperature: 0.3,
      response_format: { type: 'json_object' },
    })

    const content = completion.choices[0]?.message?.content?.trim()
    if (!content) {
      throw new Error('No quote generated by AI')
    }

    const quote = JSON.parse(content)

    // Validate and ensure structure
    if (!quote.items || !Array.isArray(quote.items) || quote.items.length === 0) {
      console.error('Invalid quote structure:', quote)
      throw new Error('AI did not generate valid quote items. Please provide more details.')
    }

    // Ensure all items have required fields and add sort_order
    quote.items = quote.items.map((item: any, index: number) => ({
      description: item.description || 'Item',
      quantity: parseFloat(item.quantity) || 1,
      unit_price: parseFloat(item.unit_price) || 0,
      amount: parseFloat(item.amount) || (parseFloat(item.quantity) || 1) * (parseFloat(item.unit_price) || 0),
      sort_order: index,
    }))

    // Validate and ensure numeric fields
    quote.client_name = quote.client_name || 'Client'
    quote.currency = currency
    quote.subtotal = parseFloat(quote.subtotal) || quote.items.reduce((sum: number, item: any) => sum + item.amount, 0)
    quote.tax_rate = parseFloat(quote.tax_rate) || 0.1
    quote.tax_amount = parseFloat(quote.tax_amount) || quote.subtotal * quote.tax_rate
    quote.total = parseFloat(quote.total) || quote.subtotal + quote.tax_amount

    return quote
  } catch (error) {
    console.error('OpenAI quote generation error:', error)
    if (error instanceof Error) {
      if (error.message.includes('JSON') || error.message.includes('parse')) {
        throw new Error('Failed to parse AI response. Please try again with more specific details.')
      }
      throw new Error(error.message)
    }
    throw new Error('Failed to generate quote. Please try again.')
  }
}
